export const schema = {
	$schema: "http://json-schema.org/draft-07/schema#",
	type: "object",
	properties: {
		business_name: {
			type: "string",
		},
		financial_data: {
			type: "object",
			properties: {
				year: {
					type: "integer",
				},
				revenue: {
					type: "object",
					properties: {
						january: { type: "number" },
						february: { type: "number" },
						march: { type: "number" },
						april: { type: "number" },
						may: { type: "number" },
						june: { type: "number" },
						july: { type: "number" },
						august: { type: "number" },
						september: { type: "number" },
						october: { type: "number" },
						november: { type: "number" },
						december: { type: "number" },
					},
					required: [
						"january",
						"february",
						"march",
						"april",
						"may",
						"june",
						"july",
						"august",
						"september",
						"october",
						"november",
						"december",
					],
				},
				total_debt: {
					type: "number",
				},
				minimum_monthly_payment: {
					type: "number",
				},
				bank_account_balance: {
					type: "object",
					properties: {
						checking: { type: "number" },
						savings: { type: "number" },
					},
					required: ["checking", "savings"],
				},
				expenses: {
					type: "object",
					properties: {
						january: { type: "number" },
						february: { type: "number" },
						march: { type: "number" },
						april: { type: "number" },
						may: { type: "number" },
						june: { type: "number" },
						july: { type: "number" },
						august: { type: "number" },
						september: { type: "number" },
						october: { type: "number" },
						november: { type: "number" },
						december: { type: "number" },
					},
					required: [
						"january",
						"february",
						"march",
						"april",
						"may",
						"june",
						"july",
						"august",
						"september",
						"october",
						"november",
						"december",
					],
				},
				profit_margin: {
					type: "object",
					properties: {
						january: { type: "number" },
						february: { type: "number" },
						march: { type: "number" },
						april: { type: "number" },
						may: { type: "number" },
						june: { type: "number" },
						july: { type: "number" },
						august: { type: "number" },
						september: { type: "number" },
						october: { type: "number" },
						november: { type: "number" },
						december: { type: "number" },
					},
					required: [
						"january",
						"february",
						"march",
						"april",
						"may",
						"june",
						"july",
						"august",
						"september",
						"october",
						"november",
						"december",
					],
				},
				cash_flow: {
					type: "object",
					properties: {
						january: { type: "number" },
						february: { type: "number" },
						march: { type: "number" },
						april: { type: "number" },
						may: { type: "number" },
						june: { type: "number" },
						july: { type: "number" },
						august: { type: "number" },
						september: { type: "number" },
						october: { type: "number" },
						november: { type: "number" },
						december: { type: "number" },
					},
					required: [
						"january",
						"february",
						"march",
						"april",
						"may",
						"june",
						"july",
						"august",
						"september",
						"october",
						"november",
						"december",
					],
				},
			},
			required: ["year", "revenue", "expenses", "profit_margin", "cash_flow"],
		},
	},
	required: ["business_name", "financial_data"],
};
